"""Render the final local report from measured artifacts, never hard-coded scores."""
import json,statistics
from train import ROOT,OUT,EVIDENCE,DATA

def main():
    comparison=json.loads((EVIDENCE/'comparison.json').read_text());manifest=json.loads((DATA/'manifest.json').read_text());completion=json.loads((OUT/'completion.json').read_text());config=json.loads((OUT/'run-config.json').read_text());selection=json.loads((OUT/'selection.json').read_text());artifact=json.loads((OUT/'artifact-manifest.json').read_text());cal=json.loads((OUT/'calibration.json').read_text())
    base=comparison['base'];candidate=comparison['candidate']
    lines=['# AI DLP bilingual fine-tuning report','',f"Status: **{cal['status']}**. Training completed; the incumbent production/default model was not changed.",'','## Measured final holdout comparison','','Both columns use the same pinned Decider 4B BF16 source quantized to MLX 4-bit/group-64. The only intended model difference is the selected LoRA adapter. The test split was excluded from training, checkpoint selection and threshold selection.','','| Metric | Base | Fine-tuned candidate |','|---|---:|---:|']
    def line(title,a,b):lines.append(f'| {title} | {a} | {b} |')
    line('Raw accuracy',f"{base['test']['accuracy']:.2%}",f"{candidate['test']['accuracy']:.2%}")
    for lang in ['ko','en']:line(lang+' document accuracy',f"{base['test']['slices']['language'][lang]['accuracy']:.2%}",f"{candidate['test']['slices']['language'][lang]['accuracy']:.2%}")
    for key in ['sensitive_allowed','ambiguous_allowed','safe_blocked','sensitive_blocked','safe_allowed','review']:
        line(key.replace('_',' '),base['test_actions'][key],candidate['test_actions'][key])
    line('Legacy 36-case raw accuracy',f"{base['legacy']['accuracy']:.2%}",f"{candidate['legacy']['accuracy']:.2%}")
    line('Permuted-option development accuracy',f"{base['permuted_dev']['accuracy']:.2%}",f"{candidate['permuted_dev']['accuracy']:.2%}")
    lines+=['','Automatic-action counts use thresholds selected separately for each model on the calibration split. Review includes explicit uncertainty and confidence below those thresholds. Raw match-to-no-match errors are separate from an actual allowed transfer.','','## Policy slices','','| Policy | Base accuracy | Candidate accuracy | Rows |','|---|---:|---:|---:|']
    for policy,stats in candidate['test']['slices']['policy_id'].items():lines.append(f"| {policy} | {base['test']['slices']['policy_id'][policy]['accuracy']:.2%} | {stats['accuracy']:.2%} | {stats['rows']} |")
    lines+=['','## Acceptance gates','']+[f"- {'PASS' if passed else 'FAIL'}: {gate}" for gate,passed in comparison['acceptance_gates'].items()]
    calibration_rows=[json.loads(line) for line in (EVIDENCE/'candidate-calibration.jsonl').read_text().splitlines()]
    diagnostic={}
    for label in ['match','no_match']:
        good=[r['probabilities'][label] for r in calibration_rows if r['prediction']==label and r['gold']==label]
        bad=[r['probabilities'][label] for r in calibration_rows if r['prediction']==label and r['gold']!=label]
        diagnostic[label]={'median_correct_score':statistics.median(good) if good else 0.0,'highest_wrong_score':max(bad,default=0.0),'correct_calibration_scores_above_highest_wrong':sum(v>max(bad,default=0.0) for v in good)}
    dm=diagnostic['match'];dn=diagnostic['no_match']
    lines+=['','## Deployment judgment','',f"The candidate routes {candidate['test_actions']['review']}/{candidate['test']['rows']} final cases ({candidate['test_actions']['review']/candidate['test']['rows']:.1%}) to review under the predeclared fixed-grid gates. Classification improved, but automatic handling coverage fell sharply, so the candidate is not promoted. Zero observed unsafe allows here must not be presented as successful autonomous operation.",'', f"Calibration-only inspection explains part of this: correct scores cluster near {dm['median_correct_score']:.3f} (match) and {dn['median_correct_score']:.3f} (no-match), below the selected gates. The highest wrong calibration scores are {dm['highest_wrong_score']:.5f} and {dn['highest_wrong_score']:.5f}; {dm['correct_calibration_scores_above_highest_wrong']} and {dn['correct_calibration_scores_above_highest_wrong']} correctly classified calibration rows respectively lie above those values. A finer or policy-specific calibration method merits a separate experiment. It was not selected against the final test, and the reported thresholds and held-out results were not changed. Fresh independent confirmation is required before claiming an improved operating point."]
    lines+=['','## Training and dataset','',f"- Dataset: {sum(s['rows'] for s in manifest['splits'].values())} synthetic decisions; {sum(s['source_families'] for s in manifest['splits'].values())} authored source families.",f"- Split rows: train {manifest['splits']['train']['rows']}, development {manifest['splits']['dev']['rows']}, calibration {manifest['splits']['calibration']['rows']}, final test {manifest['splits']['test']['rows']}.",f"- LoRA: last {config['layers']} layer(s), rank {config['rank']}, scale 16; {config['trainable_parameters']:,} trainable parameters.",f"- Completed {completion['steps']} optimizer steps over {config['epochs']} epochs, batch {config['batch_size']}; seed {config['seed']}.",f"- Training time including development scoring: {completion['elapsed_seconds']/60:.1f} minutes; process peak MLX memory {completion['peak_memory_gb']:.2f} GB.",f"- Selected step {selection['step']} by development accuracy {selection['accuracy']:.2%}.",f"- Base: Mapika/decider-4b revision {artifact['base_revision']}.",f"- Adapter SHA-256: `{artifact['adapter_sha256']}`.",f"- Candidate calibration gates: `{json.dumps(candidate['thresholds'])}`. Threshold > 1 disables that automatic action.",'','## Runtime verification','']
    api=EVIDENCE/'candidate-api-checks.json'
    if api.exists():
        result=json.loads(api.read_text());lines += [f"- Candidate API checks: {sum(result['checks'].values())}/{len(result['checks'])} passed.",f"- Composed local DLP scenarios: {sum(r['passed'] for r in result['scenarios'])}/{len(result['scenarios'])} passed.",'- These checks use an isolated local HTTP receiver and synthetic input, with a candidate override in the test client. They do not establish real provider or Windows acceptance.']
    else:lines+=['- Candidate API and composed-scenario verification not yet recorded.']
    lines+=['','## Limitations and deployment judgment','','The dataset is agent-authored and has no independent human review. Variants within a source family are correlated. These results measure short, synthetic business excerpts and fixed policy wording, not representative enterprise documents, unseen policy generalization, OCR quality, long context, or multilingual coverage beyond Korean/English. Most identity/account examples use TEST markers. Redaction, authorization, approval, audit and actual delivery remain separate deterministic controls.','', 'Score confidence is concentration over options, not a correctness guarantee. Empirical zero-error calibration does not establish zero risk. Any conversion to GGUF or deployment to a Linux/GPU runtime requires fresh inference checks and calibration. The candidate API is opt-in; the DLP policy defaults remain on the incumbent model.','','## Local artifacts','','- Training data and sealed split hashes: `judge/training/data/v1/`.','- Selected adapter and provenance: `.local/finetune/decider-4b-dlp-v1/`.','- Raw comparison, slices and score records: `evidence/judge/finetune/`.','- Reproduction and candidate service instructions: `judge/training/README.md`.']
    target=ROOT/'judge/training/FINETUNE_REPORT.md';target.write_text('\n'.join(lines)+'\n');print(target)
if __name__=='__main__':main()
