"""Authored bilingual source families. All people and organizations are synthetic.
Each translated pair shares a family and split; no translation crosses a split.
"""
SEEDS=[]
def add(domain,split,gold,ko,en):
    SEEDS.append(dict(domain=domain,split=split,gold=gold,ko=ko,en=en,family=f'{domain}-{split}-{sum(s["domain"]==domain and s["split"]==split for s in SEEDS):02d}'))

def build():
 SEEDS.clear()
 # Customer records: individual records, rather than mere discussion of data protection.
 d='customer_records';s='train'
 add(d,s,'match','{person} 고객은 {product}를 {qty}개 구매했고 대금 {money}만원 중 {small}만원이 미납이다.','Customer {person} purchased {qty} units of {product}; {small} of the {money} dollar invoice remains unpaid.')
 add(d,s,'match','배송 처리표\n성명: {person}\n주문: {product}\n배송 변경 요청: 자택 수령에서 직장 수령으로 변경.','Fulfilment row\nName: {person}\nOrder: {product}\nService request: change delivery from home to the office.')
 add(d,s,'match','{person}의 고객 계정에서 이번 달 결제 실패 {qty}건을 확인했다. 담당자는 다음 청구 전 연락할 것.','The customer account of {person} has {qty} failed payments this month. Contact them before the next billing attempt.')
 add(d,s,'match','고객별 지원 이력: {person} — {product} 고장으로 {qty}회 교환. 환급 예정액 {small}만원.','Individual support history: {person} — {qty} replacements of {product}; refund due: ${small}.')
 add(d,s,'match','{person} / 이용 상품 {product} / 누적 사용료 {money}만원 / 납부일 {day}일.','{person} / subscription {product} / accumulated usage charge ${money} / payment date day {day}.')
 add(d,s,'match','CRM 메모: {person}에게 지난 구매 불만을 사유로 다음 주문에만 적용되는 보상 포인트 {qty}점을 지급했다.','CRM note: {person} received {qty} goodwill points for dissatisfaction with their previous purchase, usable on their next order.')
 add(d,s,'match','반품 정산 — 구매자 {person}, 품목 {product}, 반품 사유 오배송, 환불 처리 대기.','Return settlement — buyer {person}, item {product}, reason wrong delivery, refund pending.')
 add(d,s,'match','상담 기록의 주체는 {person}이다. 지난주 {product} 계약을 해지했고 남은 이용료를 분할 납부하기로 했다.','This support record concerns {person}. They cancelled {product} last week and arranged instalments for the remaining service charge.')
 add(d,s,'no_match','이번 달 {product} 전체 판매 수량은 {qty}개다. 개인 이름이나 개별 주문은 포함하지 않은 상품군 집계다.','The aggregate monthly sales count for {product} is {qty}. This product-category summary has no names or individual orders.')
 add(d,s,'no_match','고객 관리 교육: 개인별 구매 내역과 결제 잔액은 접근 권한이 있는 담당자만 조회한다. 실제 고객 기록은 이 안내에 없다.','Customer-management training: restrict access to purchase histories and outstanding balances. This guidance contains no populated customer records.')
 add(d,s,'no_match','빈 주문 양식: 고객명 [입력], 구매품 [입력], 결제금액 [입력].','Blank order form: customer name [enter], item [enter], amount [enter].')
 add(d,s,'no_match','{person}은 공개 제품 설명회 발표자다. 발표 주제는 {product} 사용법이며 고객 계정 정보는 제시하지 않는다.','{person} is the speaker at a public product demonstration about using {product}; no customer account details are supplied.')
 add(d,s,'no_match','서비스 품질 지표: 평균 응답 시간 {small}분, 전체 만족도 {rate}%. 개인별 상담 이력은 제외했다.','Service-quality aggregates: average response time {small} minutes, satisfaction {rate}%; individual case histories are excluded.')
 add(d,s,'no_match','{product} 공개 사용설명서: 전원을 연결한 뒤 설정 메뉴를 연다. 고장 시 공식 지원 창구를 이용한다.','Public {product} manual: connect power, open settings, and contact the official support desk for faults.')
 add(d,s,'insufficient','첨부한 고객별 거래표를 검토해야 하지만 본문에는 표가 없고 미리보기도 실패했다.','The customer transaction attachment must be reviewed, but its table is absent and the preview failed.')
 add(d,s,'insufficient','고객 데이터 파일의 내용이 암호화되어 읽히지 않는다. 현재 보이는 것은 파일 존재 여부뿐이다.','The customer data file is encrypted and unreadable. Only the existence of the file is visible.')
 add(d,s,'insufficient','열 제목 일부만 추출됨: 대상 | 내역 | 금액. 데이터 행이 잘려 실제 개인 기록인지 알 수 없다.','Only partial column headings were extracted: subject | details | amount. Data rows are cut off, so individual records cannot be assessed.')
 add(d,s,'insufficient','구매 이력 이미지가 흐려 이름과 기록을 읽을 수 없다. 원본 확인이 필요하다.','The purchase-history image is too blurred to read names or records; the original is needed.')
 s='dev'
 add(d,s,'match','멤버십 담당 인계: {person}의 월 이용료 {money}만원을 중복 청구하여 차액 반환을 진행한다.','Membership handover: {person} was double charged a ${money} monthly fee; arrange reimbursement.')
 add(d,s,'match','{person}의 구매품 {product}는 보증 수리 중이다. 이번 방문은 올해 {qty}번째 접수다.','{person} has {product} under warranty repair; this is their {qty}th case this year.')
 add(d,s,'match','거래원장 개인 행: {person}; 대여 장비 {product}; 연체일 {day}; 미수금 {small}만원.','Individual ledger row: {person}; rented equipment {product}; overdue days {day}; receivable ${small}.')
 add(d,s,'no_match','지역별 접수 건수만 비교한다. 동부 {qty}건, 서부 {money}건이며 고객 식별 열은 없다.','Regional case counts only: east {qty}, west {money}; there are no customer identification columns.')
 add(d,s,'no_match','다음 교육은 고객별 거래정보 보호 절차를 설명하며 실습 자료는 모든 항목이 비어 있다.','The training explains protection of customer transactions; every field in its practice form is empty.')
 add(d,s,'insufficient','거래 내역 연결 문서가 만료되어 열리지 않는다. 내용 자체는 제공되지 않았다.','The linked transaction document has expired and cannot be opened; the contents were not supplied.')
 s='calibration'
 add(d,s,'match','교환 신청서에서 {person}은 {product}의 최근 결제 취소를 요청했으며 취소 수수료 {small}만원이 산정됐다.','On the exchange form, {person} requests cancellation of a recent {product} payment; the assessed cancellation fee is ${small}.')
 add(d,s,'match','상담 인계 쪽지에는 {person}의 계정 정지 원인이 사용료 {money}만원 미납이라고 적혀 있다.','The support handoff note links the suspension of {person} to ${money} in unpaid service fees.')
 add(d,s,'match','입금 대조: {person}의 주문 {product}와 입금액 {money}만원이 연결돼 있다.','Payment reconciliation links {person}, their {product} order and a ${money} deposit.')
 add(d,s,'no_match','매장 총매출 {money}만원과 상품군 점유율 {rate}%만 기록한 비식별 통계다.','This non-identifying summary lists only store revenue ${money} and product-category share {rate}%.')
 add(d,s,'no_match','공개 고객지원 FAQ: 주문을 취소하려면 계정 설정에서 취소 버튼을 누른다.','Public customer-support FAQ: to cancel an order, use the cancellation button in account settings.')
 add(d,s,'insufficient','연결된 구매자 명단과 별도 결제표가 있어야 대조할 수 있지만 두 자료 모두 누락됐다.','Matching requires the linked buyer list and separate payment table, but neither is available.')
 s='test'
 add(d,s,'match','회수 방문 일정의 비고란: {person}, {product} 할부 계약, 세 번째 납입 미처리로 담당자 방문 요청.','Collection-visit notes: {person}, instalment contract for {product}, request an agent visit after the third missed payment.')
 add(d,s,'match','분쟁 조정 자료는 신청인 {person}이 {day}일 구매한 {product}의 환불 협의 과정을 날짜별로 적었다.','A dispute-mediation record describes by date the refund negotiations for {product} purchased by claimant {person} on day {day}.')
 add(d,s,'match','VIP 이관 문서: {person}은 지난 분기에 {qty}회 주문했으며 마지막 주문 대금 {money}만원은 아직 수납되지 않았다.','VIP transfer document: {person} ordered {qty} times last quarter; ${money} for the last order is still uncollected.')
 add(d,s,'match','수납 담당자의 업무일지: {person}에게 {product} 이용료 분납 승인을 통지했고 매월 {small}만원씩 납부하기로 했다.','Collection officer diary: {person} was notified of approved instalments for {product}, paying ${small} monthly.')
 add(d,s,'no_match','서비스별 중도해지율을 표시한 차트로 개인 행이 없다. {product}: {rate}%, 전체 평균: {small}%.','A chart shows cancellation rates by service without individual rows: {product} {rate}%, overall {small}%.')
 add(d,s,'no_match','표준 구매계약서의 빈칸: 구매자____, 품목____, 금액____. 작성 예시는 없다.','Unfilled standard purchase contract: buyer____, item____, amount____. No completed example is supplied.')
 add(d,s,'no_match','{person}의 공개 기술 강연 제목은 데이터베이스 설계다. 강연 안내에는 구매나 이용 이력이 없다.','The public talk by {person} is titled Database Design; the announcement contains no purchase or service history.')
 add(d,s,'insufficient','계약자별 수납 명세가 별도 보관돼 있고 이 요청에는 표지 페이지만 전달됐다.','Per-customer collection statements are stored separately; this request contains only their cover page.')
 add(d,s,'insufficient','스캔 파일 인식 결과가 손상되어 거래 행의 주체와 내용 대부분을 복원할 수 없다.','The scan recognition output is corrupted; most subjects and transaction details cannot be recovered.')

 # Commercial pricing/cost/negotiation policies.
 d='commercial_terms';s='train'
 add(d,s,'match','{org} 전용 공급계약: 개당 납품가 {money}원, 내부 제조원가 {small}원, 계약 갱신 시 할인 상한 {rate}%.','Supply agreement specific to {org}: unit price ${money}, internal manufacturing cost ${small}, renewal discount ceiling {rate}%.')
 add(d,s,'match','영업 협상 메모: {org}에는 최초 {money}만원을 제안하고 최저 {small}만원까지 양보한다.','Sales negotiation note: open at ${money} with {org}, and concede no lower than ${small}.')
 add(d,s,'match','비공개 원가 계산표: {product} 단위당 인프라 비용 {small}, 판매 기여이익 {money}.','Internal costing sheet: {product} infrastructure cost per unit {small}, contribution margin {money}.')
 add(d,s,'match','{org}의 입찰용 제안 가격은 {money}만원이며 경쟁사가 모르는 최종 할인폭은 {rate}%다.','Our bid to {org} is ${money}; the final undisclosed discount available against competitors is {rate}%.')
 add(d,s,'match','거래처별 리베이트: {org}가 분기 목표를 채우면 구매액의 {rate}%를 사후 정산한다.','Counterparty rebate: if {org} reaches the quarterly target, retrospectively return {rate}% of its purchases.')
 add(d,s,'match','구매부 검토표에 {org}의 독점 공급조건과 납기 지연 보상액 {small}만원이 명시돼 있다.','The purchasing review lists {org} exclusive-supply terms and ${small} compensation for delivery delays.')
 add(d,s,'match','{product} 실제 수익성: 판매가가 아니라 내부 산출 기준 순마진이 {rate}%이며 외주비 {money}가 포함된다.','Actual {product} economics: the internally calculated net margin, not public list price, is {rate}%, including outsourcing cost {money}.')
 add(d,s,'match','협상팀 인계: {org}가 지불조건을 {day}일로 줄이면 계약금에서 {small}만원을 깎아줄 수 있다.','Negotiation handover: reduce the contract price by ${small} if {org} shortens payment terms to {day} days.')
 add(d,s,'no_match','공개 쇼핑몰 {product} 정가는 {money}원이며 모든 구매자에게 같은 가격이 적용된다.','The public storefront list price for {product} is ${money}, identical for every buyer.')
 add(d,s,'no_match','원가와 마진의 차이를 설명하는 교육자료다. 실제 기업이나 상품의 내부 수치는 없다.','Training explains the difference between cost and margin; it includes no actual internal figures for a company or product.')
 add(d,s,'no_match','협상 기록 양식: 상대방___, 제안가___, 양보 한도___. 아직 작성하지 않았다.','Negotiation log template: counterparty___, offer___, reservation price___. It has not been filled in.')
 add(d,s,'no_match','{org} 홈페이지 공개 할인 행사: 이번 주 전 고객에게 {rate}% 할인. 별도 개별 계약조건은 없다.','Public promotion on {org} website: {rate}% off for every customer this week, with no individually negotiated terms.')
 add(d,s,'no_match','제품 가격을 비교할 때 부가세와 배송비 포함 여부를 확인하라는 일반 구매 안내다.','General purchasing advice says to check whether quoted retail prices include tax and delivery.')
 add(d,s,'no_match','{product} 공개 요금표는 기본형 {small}원과 확장형 {money}원으로 구성된다. 내부 원가 열은 없다.','The public {product} tariff lists basic ${small} and extended ${money}; it has no internal-cost column.')
 add(d,s,'insufficient','입찰 금액과 할인 내역이 들어 있다는 첨부파일을 열 수 없어 실제 수치를 확인하지 못했다.','The attachment said to contain bid prices and discounts cannot be opened, so the actual figures are unavailable.')
 add(d,s,'insufficient','가격표 일부만 보인다. 해당 숫자가 공개 소매가인지 특정 거래처의 협상 가격인지 설명이 잘렸다.','Only part of the price sheet is visible; the explanation distinguishing public retail from negotiated counterparty prices was cut off.')
 add(d,s,'insufficient','협상 방침은 별도 문서 참조라고만 쓰여 있으며 참조 문서는 제공되지 않았다.','The note merely refers to a separate negotiation policy, but that document is not supplied.')
 add(d,s,'insufficient','원가 산출 이미지의 해상도가 낮아 항목과 수치를 구분할 수 없다.','The costing image resolution is too low to distinguish its fields or values.')
 s='dev'
 add(d,s,'match','견적 승인 기록: {org} 건만 적용할 특약으로 총액의 {rate}%를 유지보수 비용에서 제외한다.','Quote approval: a special condition solely for {org} excludes {rate}% of the total from maintenance charges.')
 add(d,s,'match','{product} 수주 손익 검토는 내부 부품 조달비 {money}와 숨겨진 간접비 {small}을 공개한다.','The internal profitability review for {product} reveals component procurement cost {money} and hidden overhead {small}.')
 add(d,s,'match','최종 제안 전에 {org}에게 제시할 수 있는 최저 수락 금액은 {money}만원으로 정했다.','Before the final offer, our lowest acceptable amount for {org} was set at ${money}.')
 add(d,s,'no_match','가격 정책 안내: 모든 가입자에게 공개된 월 정액 {money}원만 표시한다.','Pricing-policy notice: it shows only the publicly available monthly fee of ${money} for all subscribers.')
 add(d,s,'no_match','영업 교육 목차는 원가 분석, 할인 협상, 계약 갱신이며 사례 수치나 거래처명은 없다.','The sales-training contents list cost analysis, discount negotiation and renewal, without example figures or counterparties.')
 add(d,s,'insufficient','견적서 본문이 누락돼 공개 요금표인지 고객별 특약인지 확인할 수 없다.','The quotation body is missing, preventing determination of whether it is a public tariff or a customer-specific concession.')
 s='calibration'
 add(d,s,'match','{org} 거래의 이익 검토: 물류 원가 {small}만원과 내부 배부비 {qty}만원을 포함한 예상 마진 {rate}%.','Deal-profit review for {org}: margin {rate}% after logistics cost ${small} and internally allocated cost ${qty}.')
 add(d,s,'match','갱신 협의용 비공개 메모에 {org}의 라이선스 단가를 {money}원으로 낮추는 조건이 있다.','The private renewal note contains conditions for lowering {org} license unit price to ${money}.')
 add(d,s,'match','협력업체 {org}에게만 {day}일 외상 결제를 허용하고 조기 결제 시 {rate}%를 차감한다.','Only supplier {org} is offered {day}-day credit, with {rate}% deducted for early payment.')
 add(d,s,'no_match','공개 행사 부스에서 누구나 받을 수 있는 제품 소매가 안내문이다. 가격은 {money}원.','A retail-price flyer available to anyone at the public exhibition booth lists ${money}.')
 add(d,s,'no_match','내부 원가를 고객에게 노출하지 말라는 일반 지침이다. 이 문서에는 원가 수치가 없다.','General guidance says not to expose internal costs to customers; this document contains no cost figures.')
 add(d,s,'insufficient','표에 {money}라는 숫자만 남아 단가, 비용, 판매량 중 무엇인지 알 수 없다.','Only the number {money} remains in the table; it is unclear whether it is a price, cost or quantity.')
 s='test'
 add(d,s,'match','수주 심의 회의록: {org} 안건은 하청 지급액 {small}만원을 빼도 목표 공헌이익 {rate}%를 충족한다.','Order-review minutes: the {org} proposal meets a target contribution margin of {rate}% after subcontractor payment of ${small}.')
 add(d,s,'match','채널 계약 부속합의서에는 {org} 전용 매입 단가 {money}와 연말 환급률 {rate}%가 적혀 있다.','The channel-contract side letter lists a purchase unit price of {money} exclusive to {org} and a year-end refund rate of {rate}%.')
 add(d,s,'match','구매위원회 비공개 결론: {product}의 공급업체 협상에서 {money} 이상이면 계약을 포기한다.','The purchasing committee private conclusion is to abandon the {product} supplier negotiation if the price exceeds {money}.')
 add(d,s,'match','영업 시뮬레이션의 실제 기준값은 {org} 계약의 최소 총이익 {small}만원과 최대 무상 지원 {qty}시간이다.','The actual sales-simulation inputs are minimum gross profit ${small} and maximum free support {qty} hours for the {org} contract.')
 add(d,s,'no_match','공공 도서관에서 배포한 교재는 한계비용의 정의와 계산 방법만 설명한다. 기업별 원가는 없다.','The public-library textbook only explains the definition and method of marginal cost, with no company-specific costs.')
 add(d,s,'no_match','방문객 모두가 보는 매장 메뉴: {product} {money}원. 고객별 가격 구분은 하지 않는다.','Store menu visible to all visitors: {product} ${money}. Prices do not vary by customer.')
 add(d,s,'no_match','무료 세미나는 비밀 할인율 보호의 중요성을 논의하지만 구체적인 할인율이나 계약을 제시하지 않는다.','The free seminar discusses protecting confidential discounts but supplies no specific rate or deal.')
 add(d,s,'insufficient','계약 부속 가격 조건은 봉인된 별첨에 있고 현재 전송된 문서에는 첨부 목록만 있다.','The contractual pricing conditions are in a sealed annex; the submitted document has only an attachment index.')
 add(d,s,'insufficient','OCR 결과에서 거래처 이름과 숫자의 열 순서가 사라져 가격 조건의 의미를 복원할 수 없다.','OCR lost the column ordering between counterparties and numbers, preventing reconstruction of the price terms.')
 # HR records.
 d='hr_records';s='train'
 add(d,s,'match','직원 {person}의 기본급은 월 {money}만원이고 다음 분기 성과급 {small}만원을 지급한다.','Employee {person} has a monthly base salary of ${money} and will receive a ${small} bonus next quarter.')
 add(d,s,'match','인사평가: {person}은 목표 달성률 {rate}%로 개선 계획 대상이며 다음 면담은 {day}일이다.','Performance review: {person} achieved {rate}% of target and is on an improvement plan; the next meeting is on day {day}.')
 add(d,s,'match','징계위원회 기록에서 직원 {person}에게 정직 {qty}일을 결정했다.','Disciplinary committee records impose a {qty}-day suspension on employee {person}.')
 add(d,s,'match','{person} 직원의 병가 사유는 {condition} 치료이며 복귀 가능일을 인사팀과 협의 중이다.','Employee {person} is on medical leave for treatment of {condition}; HR is discussing a possible return date.')
 add(d,s,'match','보상 검토표\n직원 {person}\n현재 연봉 {money}만원\n인상 제안 {rate}%.','Compensation worksheet\nEmployee {person}\nCurrent annual salary ${money}\nProposed increase {rate}%.')
 add(d,s,'match','비공개 면담 메모: {person}의 직급을 동결하고 다음 평가까지 승진을 보류한다.','Private review note: freeze the grade of {person} and defer promotion until the next assessment.')
 add(d,s,'match','직원 {person}의 퇴직 협의안에는 특별 위로금 {money}만원과 지급일 {day}일이 명시돼 있다.','The employee departure proposal for {person} specifies an exceptional severance payment of ${money} on day {day}.')
 add(d,s,'match','{person}의 인사 파일에는 {condition}로 인한 업무 제한과 근무시간 단축 결정이 포함된다.','The personnel file for {person} includes work restrictions due to {condition} and a reduced-hours decision.')
 add(d,s,'no_match','공개 임직원 소개: {person}, 연구개발팀, 담당 업무 {product} 기획. 보상·평가 기록은 없다.','Public staff profile: {person}, R&D team, responsible for {product} planning. No compensation or review records are supplied.')
 add(d,s,'no_match','전체 직원 수 {qty}명과 부서별 인원 비율 {rate}%만 표시한 익명 통계다.','Anonymous workforce statistics show only total headcount {qty} and departmental share {rate}%.')
 add(d,s,'no_match','취업규칙은 연차 신청과 휴직 절차를 일반적으로 설명하며 특정 직원 사례를 담지 않는다.','Employment rules describe annual leave and leave-of-absence procedures generally, without individual employee cases.')
 add(d,s,'no_match','빈 성과평가 서식: 직원명____, 성과등급____, 보상____.','Empty performance review: employee name____, rating____, compensation____.')
 add(d,s,'no_match','{org} 공개 채용 공고의 직무는 보안 엔지니어이며 지원 방법과 마감일만 안내한다.','The public vacancy from {org} is for a security engineer and lists only application instructions and deadline.')
 add(d,s,'no_match','직원 건강정보를 보호해야 한다는 교육 안내이며 진단명이나 개인별 내역은 없다.','Training explains the need to protect employee health information and contains no diagnoses or individual records.')
 add(d,s,'insufficient','직원별 보상표가 있다는 안내만 있고 실제 표는 누락되어 내용을 볼 수 없다.','The message mentions an individual compensation sheet, but the sheet is missing and cannot be inspected.')
 add(d,s,'insufficient','인사기록 파일이 잠겨 있어 직원 이름과 평가 내용을 읽을 수 없다.','The personnel-record file is locked; employee names and evaluations cannot be read.')
 add(d,s,'insufficient','직원 목록과 점수표의 연결 키가 누락돼 점수가 누구의 평가인지 알 수 없다.','The linking key between staff list and score table is missing, so it is unclear whose evaluations the scores represent.')
 add(d,s,'insufficient','휴직 자료 스캔에서 대상자와 사유 부분이 모두 잘려 나갔다.','The leave-record scan is cut off at both the employee identity and reason fields.')
 s='dev'
 add(d,s,'match','{person}의 연봉 조정 회의는 동료 대비 급여가 {rate}% 낮다며 {small}만원 추가 인상을 권고했다.','The salary review for {person} recommends a ${small} raise because their pay is {rate}% below peers.')
 add(d,s,'match','인사팀은 {person}의 반복 지각으로 서면 경고 조치를 인사이력에 등재했다.','HR added a written warning to the personnel history of {person} for repeated lateness.')
 add(d,s,'match','{person}의 산업재해 치료 경과와 직무 복귀 평가가 직원별 복귀계획에 기록돼 있다.','The individual return-to-work plan records the occupational-injury treatment progress and fitness assessment of {person}.')
 add(d,s,'no_match','익명 조사에서 전체 직원의 {rate}%가 교육 확대를 원한다고 답했다.','In an anonymous survey, {rate}% of all employees requested more training.')
 add(d,s,'no_match','인사평가 가이드의 제목과 항목 설명만 있으며 실제 평가 대상자는 없다.','The review guide contains only headings and field explanations, with no actual employee assessments.')
 add(d,s,'insufficient','급여 내역은 다른 시스템에 있으며 이 화면은 조회 실패 알림만 보여준다.','Payroll details are in another system; this screen shows only a failed-query notification.')
 s='calibration'
 add(d,s,'match','관리자 인계: {person}의 수습평가 결과가 미달이므로 수습 기간을 {qty}개월 연장한다.','Manager handover: extend the probation of {person} by {qty} months due to an unsatisfactory probation assessment.')
 add(d,s,'match','{person}에게 배정할 스톡옵션 {qty}주와 개인별 베스팅 예외가 보상위원회 안건에 포함돼 있다.','The compensation committee agenda includes {qty} stock options for {person} and an individual vesting exception.')
 add(d,s,'match','직원 {person}의 휴직 연장은 {condition} 치료 소견을 근거로 승인됐다.','The extension of leave for employee {person} was approved based on a treatment opinion for {condition}.')
 add(d,s,'no_match','회사 대표 번호와 공개 업무 담당자 이름 {person}만 나열한 문의 안내다.','The contact notice lists only the company main number and the public work contact name {person}.')
 add(d,s,'no_match','보상제도 설명회는 등급 체계만 소개하며 개인별 급여나 등급은 발표하지 않는다.','The compensation briefing explains the grade structure without disclosing individual pay or ratings.')
 add(d,s,'insufficient','성과검토 첨부의 일부 페이지가 없어서 누구의 점수인지 판단할 수 없다.','Pages are missing from the performance-review attachment, so the person associated with the score cannot be determined.')
 s='test'
 add(d,s,'match','승진심사 비공개 표결에서 {person}은 리더십 항목 미달로 추천 대상에서 제외됐다.','In the private promotion-panel vote, {person} was excluded from recommendation for failing the leadership criterion.')
 add(d,s,'match','급여 정산 이의 신청서에는 {person}의 야근 수당 {small}만원과 기존 지급액 {money}만원이 적혀 있다.','The payroll dispute form lists overtime pay of ${small} and an existing payment of ${money} for {person}.')
 add(d,s,'match','복직 지원 회의록: {person}의 {condition} 증상이 남아 야간 근무를 제한하기로 했다.','Return-to-work support minutes: restrict night shifts because symptoms of {condition} persist for {person}.')
 add(d,s,'match','조직 개편의 개인별 처우안에서 {person}의 계약을 갱신하지 않고 합의금 {money}만원을 지급한다.','The reorganization individual settlement proposes non-renewal of {person} contract and a settlement payment of ${money}.')
 add(d,s,'no_match','분기별 인력 현황 보고에는 부서 수 {qty}와 전체 채용 증가율 {rate}%만 있다.','The quarterly workforce overview contains only {qty} departments and an overall hiring growth rate of {rate}%.')
 add(d,s,'no_match','강의 자료는 해고 절차의 일반 원칙을 소개하지만 실제 직원의 처분 사례는 없다.','The lecture describes general dismissal-procedure principles without an actual employee disposition.')
 add(d,s,'no_match','컨퍼런스 웹사이트의 발표자 소개는 {person}의 소속과 공개 발표 주제만 제공한다.','The conference website biography supplies only the affiliation and public talk topic of speaker {person}.')
 add(d,s,'insufficient','봉인된 평가 봉투의 수신 부서만 촬영됐고 봉투 속 직원별 평가는 보이지 않는다.','Only the destination department on a sealed review envelope was photographed; the employee evaluations inside are not visible.')
 add(d,s,'insufficient','인사 원장 PDF의 폰트가 깨져 직원명과 처우 내용을 해독할 수 없다.','Broken fonts in the personnel-ledger PDF prevent deciphering employee names and treatment details.')

 # Internal technical artifacts versus generic and published technology.
 d='proprietary_technical';s='train'
 add(d,s,'match','사내 미공개 {product} 탐지 엔진은 위험 점수를 r=7*a+3*b로 계산하고 r>{qty}일 때 격리 큐를 호출한다.','Our unreleased {product} detection engine computes r=7*a+3*b and invokes the isolation queue when r>{qty}.')
 add(d,s,'match','내부 운영 설정: {org} 전용 서비스는 10.42.{small}.7:{port}에서 관리 API를 노출하고 /ops/override 경로로 재처리한다.','Private operations configuration: the dedicated {org} service exposes its admin API on 10.42.{small}.7:{port} and reprocesses through /ops/override.')
 add(d,s,'match','아직 공개하지 않은 자체 프로토콜 설계는 첫 8바이트를 세션 식별자로 쓰고 다음 필드에 장치 서명 검증 결과를 넣는다.','Our unpublished protocol design uses the first eight bytes as a session identifier and the next field for the device signature-verification result.')
 add(d,s,'match','내부 미해결 취약점: {product}의 /admin/export는 역할 검증 없이 export_all 플래그를 받아 전체 기록을 내보낸다.','Unremediated internal flaw: /admin/export in {product} accepts export_all without checking roles and exports every record.')
 add(d,s,'match','비공개 소스 발췌: score = customer_weight * 0.73 + recency * 0.27; 회사 추천 엔진의 현재 운영 공식이다.','Private source excerpt: score = customer_weight * 0.73 + recency * 0.27; this is the current production formula of our recommendation engine.')
 add(d,s,'match','사내 장애 대응 토폴로지에는 인증 서비스 -> edge-internal -> 저장소 shard-{qty}의 연결 순서와 비공개 포트 {port}가 적혀 있다.','The private incident-response topology specifies auth service -> edge-internal -> storage shard-{qty}, with private port {port}.')
 add(d,s,'match','연구실 미출원 설계: {product} 센서 필터 계수는 [0.11,0.38,0.51]이고 보정 주기는 {qty}회다.','Unfiled lab design: the {product} sensor uses filter coefficients [0.11,0.38,0.51] and recalibrates every {qty} cycles.')
 add(d,s,'match','개발팀 내부 메모: 새 {product} 펌웨어는 부팅 후 slot_B 검증 실패 시 서명 재확인 없이 slot_A로 이동한다. 아직 수정 전이다.','Internal development note: the new {product} firmware falls back from failed slot_B verification to slot_A without rechecking the signature; it is not yet fixed.')
 add(d,s,'no_match','공개 Python 입문 예제: def add(a,b): return a+b. 어떤 회사의 내부 구현도 포함하지 않는다.','Public beginner Python example: def add(a,b): return a+b. It contains no company-internal implementation.')
 add(d,s,'no_match','TLS는 통신 내용을 암호화하는 표준이라는 개괄적 설명이며 내부 네트워크 구성은 없다.','A high-level explanation says TLS is a standard for encrypting communications; no internal network configuration is given.')
 add(d,s,'no_match','{product} 공개 소개서는 빠른 탐지와 쉬운 운영을 장점으로 소개하지만 구현 세부사항은 공개하지 않는다.','The public {product} brochure advertises fast detection and easy operation, without revealing implementation details.')
 add(d,s,'no_match','사내 소스코드가 존재한다는 안내만 있고 실제 코드, 설정, 설계 내용은 전혀 싣지 않았다.','The notice only states that internal source code exists; it contains no actual code, configuration or design details.')
 add(d,s,'no_match','공개 HTTP 문서는 GET과 POST의 일반적 의미를 설명한다. 특정 내부 엔드포인트는 없다.','The published HTTP guide explains GET and POST generally, with no particular private endpoint.')
 add(d,s,'no_match','빈 시스템 설계 양식: 구성요소___, 내부 주소___, 통신 규약___.','Blank system-design template: component___, internal address___, protocol___.')
 add(d,s,'insufficient','설계 파일이 손상되어 다이어그램과 설정을 열 수 없다. 원본을 복원해야 검사할 수 있다.','The design file is corrupted, so diagrams and configuration cannot be opened; inspection requires restoration.')
 add(d,s,'insufficient','기술 첨부가 링크로만 제공됐으나 링크 접근이 실패해 코드 내용을 알 수 없다.','The technical attachment is only a link, and access failed, leaving the code unavailable.')
 add(d,s,'insufficient','소스 추출이 중단되어 함수 이름 일부만 남고 구현과 출처 설명이 사라졌다.','Source extraction stopped, leaving partial function names without implementation or provenance.')
 add(d,s,'insufficient','구성도 이미지의 해상도가 낮아 주소와 연결 관계를 읽을 수 없다.','The configuration diagram resolution is too low to read addresses or connections.')
 s='dev'
 add(d,s,'match','내부 설계 검토에서 아직 공개하지 않은 {product} 저장 형식은 16비트 길이 필드 뒤에 delta-encoded 센서값을 넣는다.','The internal design review specifies that the unpublished {product} storage format places delta-encoded sensor values after a 16-bit length field.')
 add(d,s,'match','운영 전용 절차서에는 cluster-{qty}의 비공개 관리 포트 {port}와 /internal/resync 호출 순서가 적혀 있다.','The operations-only procedure lists private admin port {port} for cluster-{qty} and the /internal/resync call sequence.')
 add(d,s,'match','개발 보안 점검: 미수정 {product} 서비스가 첨부파일명을 검증하지 않아 상위 경로 파일을 덮어쓸 수 있다.','Development security finding: the unpatched {product} service fails to validate attachment names and can overwrite parent-directory files.')
 add(d,s,'no_match','공개 강의는 해시 함수의 일반 성질과 간단한 공개 예제를 설명한다.','The public lecture explains general hash-function properties and a simple published example.')
 add(d,s,'no_match','제품 발표자료는 새로운 검색 기능이 추가됐다고만 말하고 비공개 알고리즘은 설명하지 않는다.','The product announcement only says a search feature was added and does not describe its private algorithm.')
 add(d,s,'insufficient','기술 원문 다운로드가 끊겨 처음 몇 바이트만 남아 내용을 해석할 수 없다.','The technical artifact download was interrupted, leaving only a few uninterpretable bytes.')
 s='calibration'
 add(d,s,'match','비공개 배포 메모: {product}의 staging-auth는 검증 예외 헤더 X-Internal-Replay를 받으면 재인증을 생략한다.','Private deployment note: staging-auth in {product} skips reauthentication on the exception header X-Internal-Replay.')
 add(d,s,'match','아직 출원하지 않은 검출 방식은 세 센서의 시차를 [2,5,9]로 보정하고 가중합 {rate}/100으로 판단한다.','The not-yet-filed detection method corrects three sensor delays by [2,5,9] and uses a weighted sum of {rate}/100.')
 add(d,s,'match','내부 코드리뷰는 {product}의 권한 캐시 키에 조직 ID가 빠져 다른 조직의 허용 결과를 재사용하는 미해결 버그를 설명한다.','An internal code review describes an unfixed {product} bug: tenant ID is missing from the authorization-cache key, reusing another tenant permission result.')
 add(d,s,'no_match','오픈소스 교육은 배열을 정렬하는 공개 예제를 재현하며 회사 내부 로직은 없다.','The open-source lesson reproduces a public array-sorting example with no private company logic.')
 add(d,s,'no_match','백서 요약은 제품이 머신러닝을 쓴다고만 설명하며 가중치나 비공개 설정은 포함하지 않는다.','The whitepaper summary merely says the product uses machine learning, without weights or private configuration.')
 add(d,s,'insufficient','엔지니어링 도면의 주요 영역이 빈 칸으로 렌더링돼 설계 내용을 확인할 수 없다.','Major regions of the engineering drawing render blank, preventing inspection of the design.')
 s='test'
 add(d,s,'match','출시 전 설계 심의 문서: {product} 재시도 큐는 업무키와 5분 시간창을 합쳐 중복을 제거하며 실패 {qty}회 이후 우회 큐로 보낸다.','Pre-release design review: the {product} retry queue deduplicates by business key plus a five-minute window and routes to bypass after {qty} failures.')
 add(d,s,'match','비공개 데이터센터 인수 문서에 복제 대상 10.73.{small}.8:{port}과 운영 역할 전환 순서가 담겨 있다.','The private datacenter handover lists replication target 10.73.{small}.8:{port} and the production role-switch sequence.')
 add(d,s,'match','수정 전 보안 이슈의 재현 조건: {product}에서 같은 승인 ID를 재전송하면 사용 완료 여부를 확인하지 않아 명령이 다시 실행된다.','Reproduction of an unfixed security issue: resubmitting the same approval ID in {product} executes the command again because consumed status is not checked.')
 add(d,s,'match','자체 영상 모델의 비공개 후처리 사양은 경계 픽셀 {qty}개를 제외한 뒤 임계값 0.67로 소수 클래스를 병합한다.','The proprietary vision model private postprocessing spec excludes {qty} boundary pixels, then merges minority classes at a 0.67 threshold.')
 add(d,s,'no_match','표준 문서 해설은 공개 DNS 레코드 종류와 의미만 설명한다. 내부 도메인이나 주소는 없다.','The standards commentary only explains public DNS record types and meanings, with no private domains or addresses.')
 add(d,s,'no_match','개발자 행사 안내는 비공개 알고리즘 유출 방지라는 발표 제목과 발표시간만 제공한다.','The developer-event announcement provides only a talk title about preventing private algorithm leaks and its time.')
 add(d,s,'no_match','공개 실습 코드: for item in items: print(item). 사내 제품과 연결된 구현은 아니다.','Public exercise code: for item in items: print(item). It is not an implementation from an internal product.')
 add(d,s,'insufficient','기밀 기술도면이 담긴 파일의 암호가 없어서 구성요소를 볼 수 없다.','The password for the file containing confidential technical drawings is unavailable, so its components cannot be viewed.')
 add(d,s,'insufficient','소스 차이 비교 화면이 비어 있고 변경 파일 이름도 잘려 실제 구현을 알 수 없다.','The source diff view is blank and filenames are truncated, leaving the actual implementation unknown.')
 d='strategic_finance';s='train'
 add(d,s,'match','발표 전 경영 전망: 다음 분기 매출 {money}억원, 영업이익률 {rate}%를 예상한다.','Unreleased management forecast: next-quarter revenue ${money} million, operating margin {rate}%.')
 add(d,s,'match','이사회 비공개 안건: {org} 인수에 {money}억원을 배정하고 다음달 실사를 시작한다.','Private board agenda: allocate ${money} million to acquire {org}, with diligence starting next month.')
 add(d,s,'match','아직 공시하지 않은 결산 수치: 순손실 {money}억원과 현금 잔액 {small}억원.','Unannounced closing figures: net loss ${money} million and cash balance ${small} million.')
 add(d,s,'match','회사 내부 자금조달안은 신주 {qty}만 주를 발행해 {money}억원을 유치하는 것이다.','The internal corporate financing proposal issues {qty} thousand new shares to raise ${money} million.')
 add(d,s,'match','비공개 사업전략 예산: 해외 진출 {money}억원, 신규 연구소 {small}억원.','Private corporate strategic budget: ${money} million for overseas expansion and ${small} million for a new lab.')
 add(d,s,'match','재무팀 전용 추정: 올해 말 회사의 가용현금은 {small}억원으로 감소하며 아직 외부 발표 전이다.','Finance-only estimate: year-end available corporate cash falls to ${small} million; this has not been released.')
 add(d,s,'match','비밀 투자 유치 제안서: 기업가치 {money}억원 기준으로 지분 {rate}%를 제공한다.','Confidential fundraising proposal: offer {rate}% equity at a ${money} million company valuation.')
 add(d,s,'match','전략위원회는 비공개로 {org} 사업부 매각을 검토하고 예상 대금을 {money}억원으로 잡았다.','The strategy committee privately considers selling the {org} division for estimated proceeds of ${money} million.')
 add(d,s,'no_match','이미 공시된 전년도 회사 매출은 {money}억원이다. 누구나 열람하는 연차보고서 수치다.','Last year company revenue was ${money} million, already disclosed in the public annual report.')
 add(d,s,'no_match','현금흐름이란 일정 기간 유입과 유출된 현금을 나타내는 일반적인 회계 개념이다.','Cash flow is the general accounting concept of cash entering and leaving during a period.')
 add(d,s,'no_match','기업 인수 절차에 관한 공개 교육자료이며 특정 인수 대상이나 내부 계획은 없다.','Public training on acquisition procedures, without any specific target or internal plan.')
 add(d,s,'no_match','예산 양식: 예상 매출___, 투자액___, 승인일___. 수치는 비어 있다.','Budget template: expected revenue___, investment___, approval date___. No figures are filled in.')
 add(d,s,'no_match','공시 홈페이지에 게시된 확정 배당금은 주당 {small}원이다.','The finalized dividend published on the disclosure website is ${small} per share.')
 add(d,s,'no_match','{person} 고객의 이번 주문 청구액은 {money}원이다. 회사 전체 전망이나 전략은 없다.','Customer {person} owes ${money} for this order. No company-wide forecast or strategy is included.')
 add(d,s,'insufficient','재무 전망 파일을 첨부했다고 하지만 첨부가 없어 예상 수치를 볼 수 없다.','A financial forecast is said to be attached, but the attachment is absent, so its figures cannot be viewed.')
 add(d,s,'insufficient','이사회 전략 문서 링크의 권한이 없어 내용을 확인하지 못했다.','The board strategy document link is inaccessible, leaving its contents unknown.')
 add(d,s,'insufficient','손상된 결산 표에서 숫자와 공개 여부 설명이 모두 누락됐다.','The damaged closing table is missing both figures and disclosure-status information.')
 add(d,s,'insufficient','투자안 스캔이 흐려 회사와 금액을 판독할 수 없다.','The investment proposal scan is too blurred to read the company and amounts.')
 s='dev'
 add(d,s,'match','경영회의 내부 자료: 다음 회계연도 구독 매출 목표 {money}억원은 아직 발표하지 않았다.','Internal management meeting: next fiscal year subscription revenue target of ${money} million is not yet announced.')
 add(d,s,'match','비공개 차입 계획은 전환사채 {money}억원을 발행하고 {qty}개월 후 상환한다.','The private borrowing plan issues ${money} million of convertible debt, repayable after {qty} months.')
 add(d,s,'match','공개 전 투자위원회 결정: {org} 지분 {rate}% 확보에 {money}억원을 사용한다.','Unreleased investment committee decision: spend ${money} million to obtain {rate}% of {org}.')
 add(d,s,'no_match','언론에 이미 발표한 작년 영업이익은 {money}억원이며 내부 전망은 싣지 않았다.','Last year operating profit of ${money} million was already announced to the press; no internal forecast is given.')
 add(d,s,'no_match','금융 교육에서는 부채와 자본의 일반적인 차이를 설명한다.','The finance lesson explains the general difference between debt and equity.')
 add(d,s,'insufficient','공개 예정 실적 첨부가 비어 있어 실제 실적을 읽을 수 없다.','The attachment for upcoming results is empty, so the actual results cannot be read.')
 s='calibration'
 add(d,s,'match','CFO 전용 시나리오: 외부 미공개인 내년 적자 예상액은 {money}억원이다.','CFO-only scenario: next year expected deficit is ${money} million and has not been released externally.')
 add(d,s,'match','비공개 합병 준비 메모에 {org}와의 주식 교환비율 1:{qty}가 적혀 있다.','The private merger preparation memo specifies a 1:{qty} share exchange ratio with {org}.')
 add(d,s,'match','아직 발표 전인 전사 구조개편에는 신규 시설 투자 {money}억원을 취소하는 예산안이 포함된다.','The unannounced company-wide restructuring includes a budget proposal cancelling ${money} million of new facility investment.')
 add(d,s,'no_match','거래소가 공개한 지난 분기 매출액 {money}억원을 그대로 인용했다.','This quotes last quarter revenue of ${money} million already published by the exchange.')
 add(d,s,'no_match','재무 분석 입문서는 손익계산서의 각 항목이 의미하는 바를 설명한다.','The introductory financial analysis book explains what income-statement fields mean.')
 add(d,s,'insufficient','전략 투자 제안서 페이지가 잘려 제목만 있고 거래 내용은 없다.','The strategic investment proposal page is cropped to the title, with transaction contents unavailable.')
 s='test'
 add(d,s,'match','감사위원회 비공개 잠정 집계: 아직 공표 전인 이번 반기 손상차손 {money}억원을 반영해야 한다.','Private audit committee preliminary tally: recognize ${money} million impairment this half-year, before public announcement.')
 add(d,s,'match','비공개 자금운용 회의록: 회사 유동성 확보를 위해 {org} 자산을 {money}억원에 매각 추진한다.','Private treasury minutes: pursue sale of {org} assets for ${money} million to secure corporate liquidity.')
 add(d,s,'match','대외비 사업 포트폴리오 계획은 다음해 연구개발 예산 {money}억원 중 {rate}%를 새 사업에 배정한다.','The confidential business portfolio plan allocates {rate}% of next year ${money} million R&D budget to a new venture.')
 add(d,s,'match','발표를 앞둔 내부 추산에서 다음 분기 회사 현금 소진 규모는 {money}억원이며 생존 기간은 {qty}개월이다.','The internal estimate ahead of announcement projects next-quarter corporate cash burn of ${money} million and runway of {qty} months.')
 add(d,s,'no_match','정부 통계에 공개된 업종 평균 성장률은 {rate}%이며 특정 회사의 비공개 전망은 없다.','The industry average growth rate of {rate}% is published in government statistics, with no private company forecast.')
 add(d,s,'no_match','주주에게 이미 배포된 과거 사업보고서의 자산 총액 {money}억원을 재인용한다.','This repeats total assets of ${money} million from a historical report already distributed to shareholders.')
 add(d,s,'no_match','{person}이 {product} 구입비 {money}원을 지불한 영수증이며 기업 전략은 담기지 않았다.','A receipt shows {person} paid ${money} for {product}; it contains no corporate strategy.')
 add(d,s,'insufficient','회사 인수 제안은 암호화된 압축파일에 있는데 복호화에 실패해 내용은 알 수 없다.','The acquisition proposal is inside an encrypted archive whose decryption failed, leaving its content unknown.')
 add(d,s,'insufficient','재무 계획 표의 행 이름과 값이 서로 분리되어 어느 회사의 어떤 기간인지 알 수 없다.','The financial plan table labels and values are separated, leaving the company and period indeterminate.')
 d='personal_sensitive';s='train'
 add(d,s,'match','진료 기록: {person}의 진단은 {condition}이며 다음 진료는 {day}일이다.','Medical record: {person} was diagnosed with {condition}; next visit is on day {day}.')
 add(d,s,'match','환자 {person}에게 {condition} 치료 목적으로 약물을 처방했고 {qty}일 후 재검한다.','Patient {person} was prescribed medication for {condition}, with reassessment in {qty} days.')
 add(d,s,'match','신분 확인 자료: {person}의 여권번호는 TEST-P{money}{small}이다.','Identity verification record: {person} has passport number TEST-P{money}{small}.')
 add(d,s,'match','개인 금융 명세: {person}, 계좌번호 TEST-AC{money}{qty}, 잔액 {small}만원.','Personal financial statement: {person}, account TEST-AC{money}{qty}, balance ${small}.')
 add(d,s,'match','등록자 {person}의 지문 템플릿 ID bio-{money}와 특징점 배열 [12,37,81,94]를 저장했다.','Registrant {person} has fingerprint template bio-{money}, with minutiae array [12,37,81,94].')
 add(d,s,'match','의료 상담 노트에 {person}의 {condition} 병력과 최근 치료 경과가 기록돼 있다.','The medical consultation note records {person} history of {condition} and recent treatment progress.')
 add(d,s,'match','신분증 사본 추출: 성명 {person}, 정부 발급 식별번호 TEST-ID-{money}-{qty}.','Identity-card extraction: name {person}, government-issued identifier TEST-ID-{money}-{qty}.')
 add(d,s,'match','생체 등록 결과: {person}의 홍채 코드 iris:{money}:A7F2와 등록일 {day}일.','Biometric enrolment: {person} iris code iris:{money}:A7F2, registered on day {day}.')
 add(d,s,'no_match','{condition}의 일반적인 예방 수칙을 설명하며 환자 이름이나 개인 진료 기록은 없다.','General prevention advice for {condition}, with no patient names or individual medical records.')
 add(d,s,'no_match','진료 신청 빈 양식: 성명___, 증상___, 복용약___.','Blank appointment form: name___, symptoms___, medication___.')
 add(d,s,'no_match','공개 업무 명함에는 {person}의 이름과 영업 담당 직책만 있다.','The public business card only lists {person} name and sales role.')
 add(d,s,'no_match','익명 통계: 지난달 전체 진료 건수는 {money}건이다. 개인을 구분하는 항목은 없다.','Anonymous aggregate: {money} consultations last month, with no individual identifiers.')
 add(d,s,'no_match','생체인식의 원리를 설명하는 교재로 등록자의 실제 특징값은 없다.','A textbook explaining biometric principles, without actual enrolled-person feature values.')
 add(d,s,'no_match','여권 갱신 안내는 준비 서류를 나열하며 신청인의 신분번호는 싣지 않았다.','Passport renewal guidance lists required documents without any applicant identity number.')
 add(d,s,'insufficient','검사 결과 파일을 열지 못해 이름과 진단 내용 모두 확인할 수 없다.','The test-result file cannot be opened, so neither the name nor diagnosis can be checked.')
 add(d,s,'insufficient','개인 계좌 문서 스캔이 흐려 명의인과 번호를 읽을 수 없다.','The personal account document scan is too blurred to read the holder and number.')
 add(d,s,'insufficient','생체 등록 파일은 헤더만 남고 사람과 템플릿을 연결하는 부분이 유실됐다.','Only the biometric enrolment header remains; the person-to-template linkage is lost.')
 add(d,s,'insufficient','신분증 이미지가 로드되지 않아 기재 정보를 알 수 없다.','The identity-card image does not load, leaving its recorded information unknown.')
 s='dev'
 add(d,s,'match','진료 회신: {person}의 {condition}에 대한 추적 검사를 {qty}주 후 진행한다.','Clinical reply: schedule follow-up tests for {person} condition of {condition} in {qty} weeks.')
 add(d,s,'match','은행 확인서: 예금주 {person}, 개인계좌 TEST-BK-{money}, 입출금 잔액 {small}만원.','Bank confirmation: holder {person}, personal account TEST-BK-{money}, balance ${small}.')
 add(d,s,'match','인증 등록 자료는 {person}의 얼굴 임베딩 [0.17,0.82,0.43]을 포함한다.','The authentication enrolment material contains {person} face embedding [0.17,0.82,0.43].')
 add(d,s,'no_match','{person}이 공개 세미나에서 발표한다는 일정만 있다.','The schedule only states that {person} will speak at a public seminar.')
 add(d,s,'no_match','환자 정보 보호 교육이며 개별 환자 정보나 실제 기록은 포함하지 않는다.','Patient privacy training containing no individual patient details or populated records.')
 add(d,s,'insufficient','검진표의 이름 칸이 잘리고 여러 사람의 수치가 섞여 연결을 알 수 없다.','The screening form name field is cropped and values from several people are mixed, so linkage is unknown.')
 s='calibration'
 add(d,s,'match','의료 기록 전송본: {person}은 {condition}으로 입원했고 퇴원일은 {day}일이다.','Transferred medical record: {person} was hospitalized for {condition}, with discharge on day {day}.')
 add(d,s,'match','본인 확인 목록: {person} — 정부 신분증번호 TEST-GOV-{money}{qty}.','Identity check list: {person} — government identity-card number TEST-GOV-{money}{qty}.')
 add(d,s,'match','개인 자산 자료에 {person}의 금융계좌 TEST-SV-{money}와 예치금 {small}만원이 있다.','The personal asset record includes {person} financial account TEST-SV-{money} and deposit of ${small}.')
 add(d,s,'no_match','건강 캠페인 포스터는 충분한 수면을 권장하고 어떤 개인의 진단도 싣지 않는다.','The health campaign poster recommends sufficient sleep without any individual diagnosis.')
 add(d,s,'no_match','통계 보고서는 이름 없이 전체 참가자 {money}명의 평균 검사 점수만 제시한다.','The statistical report gives only the average test score of {money} unnamed participants.')
 add(d,s,'insufficient','신분 확인 첨부에서 일부 숫자만 추출돼 개인과 번호 종류를 식별할 수 없다.','Only partial digits were extracted from the identity attachment, leaving the person and number type unknown.')
 s='test'
 add(d,s,'match','비공개 물리치료 기록: {person}은 {condition} 때문에 주 {qty}회 치료를 받고 있다.','Private physiotherapy record: {person} receives treatment {qty} times weekly for {condition}.')
 add(d,s,'match','보험 심사에 제출한 개인 검사 결과에 {person}의 {condition} 진단과 약물 복용 내역이 담겨 있다.','Individual test results submitted for insurance review contain {person} diagnosis of {condition} and medication history.')
 add(d,s,'match','생체 인증 이전 명세: 사용자 {person}, 손바닥 정맥 특징값 [91,24,66,08], 템플릿 pv-{money}.','Biometric migration specification: user {person}, palm-vein features [91,24,66,08], template pv-{money}.')
 add(d,s,'match','개인 대출 심사 원장: {person}, 상환계좌 TEST-LN-{money}, 해당 계좌 잔액 {small}만원.','Personal loan review ledger: {person}, repayment account TEST-LN-{money}, account balance ${small}.')
 add(d,s,'no_match','공공기관 안내는 운전면허증 분실 시 신고 절차를 설명하며 실제 면허번호는 없다.','Public agency guidance explains how to report a lost driving licence, with no actual licence numbers.')
 add(d,s,'no_match','{person}의 공개 저자 소개에는 소속과 출간한 책 제목만 있다.','The public author biography for {person} contains only affiliation and published book titles.')
 add(d,s,'no_match','이름과 식별자를 수집하지 않은 지역 건강 설문의 전체 응답률은 {rate}%다.','The regional health survey collected no names or identifiers and has an overall response rate of {rate}%.')
 add(d,s,'insufficient','두 페이지의 임상 기록이 뒤섞여 각 진단이 어느 환자의 것인지 확인할 수 없다.','Two pages of clinical records are interleaved, making it impossible to determine which patient each diagnosis belongs to.')
 add(d,s,'insufficient','금융계좌 확인 파일은 압축 해제 오류로 본문 전체가 누락됐다.','The financial account verification file has no readable body because decompression failed.')
