'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type Policy={id:string;name:string;enabled:boolean;question:string;match_description:string;no_match_description:string;effect:'block'|'review';threshold:number;uncertainty_action:'block'|'review';model_id:string;scenarios:string[];destinations:string[]};
type Scenario={id:string;title:string;description:string;protected_text:string;allowed_text:string;requirement:string};
type Snapshot={revision:number;policies:Policy[]};
type Status={jev_api_connected:boolean;policy:Snapshot;scenarios:Scenario[];models:{id:string;downloaded:boolean;weight_bytes:number}[]};
type Decision={id:string;action:string;reason:string;policy_revision:number;delivered:boolean;delivery_id:string|null;approval_id:string|null;request_digest:string;elapsed_ms:number;extraction:{format:string;complete:boolean};findings:{policy_id:string;choice:string;scores:Record<string,number>;model_id:string;latency_ms:number;cached:boolean}[]};
type Run={scenario_id:string;variant:string;text?:string;filename?:string;file_base64?:string;approval_id?:string};
type Event={id:string;kind:string;created_at:number;data:Record<string,unknown>};
type Benchmark={reports:{model:string;p50_ms:number;p95_ms:number;held_out:{all:{n:number;raw_correct:number;false_allow:number;false_block:number;reviews:number;safe_allow:number;safe_count:number}}}[]};
const labels:Record<string,string>={allow:'허용',block:'차단',redact:'식별자 제거 후 허용',review:'검토 대기',match:'정책에 해당',no_match:'해당 없음',insufficient:'판단 정보 부족'};
const reasons:Record<string,string>={jev_api_timeout:'판단 API 응답 시간이 초과되어 전송을 차단했습니다.',jev_api_unavailable:'판단 API에 연결할 수 없어 전송을 차단했습니다.',jev_invalid_response:'판단 API 응답이 유효하지 않아 전송을 차단했습니다.',policy_allowed:'적용 정책을 통과했습니다.',judge_uncertain:'모델 판단이 불확실해 전송을 보류했습니다.',semantic_policy_match:'콘텐츠가 보호 정책에 해당합니다.',source_acl_denied_before_retrieval:'검색 권한이 없어 자료를 제외했습니다.',label_prohibits_ai_processing:'AI 처리 금지 레이블에 따라 제외했습니다.',supported_identifiers_redacted:'지원하는 개인정보 식별자를 제거했습니다.',direct_identifier_detected:'직접 식별자가 있어 외부 전송을 차단했습니다.',secret_detected:'인증정보 또는 비밀키가 탐지되었습니다.',bound_human_approval:'동일한 내용·정책에 대한 관리자의 일회성 승인을 적용했습니다.',judge_busy:'모델이 다른 요청을 처리 중입니다.',judge_timeout:'모델 응답 제한 시간을 초과했습니다.',input_token_limit:'모델의 입력 길이 제한을 초과했습니다.',delivery_outcome_unknown:'수신 응답을 확인하지 못했습니다. 전송 여부를 확인한 후 조치하세요.'};
async function call<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/judge/'+path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const value=await r.json();if(!r.ok)throw new Error(value.message||'요청 실패');return value;}
export default function JudgeLab(){
 const [status,setStatus]=useState<Status|null>(null),[policy,setPolicy]=useState<Snapshot|null>(null),[benchmark,setBenchmark]=useState<Benchmark|null>(null),[events,setEvents]=useState<Event[]>([]);
 const [tab,setTab]=useState('run'),[scenarioId,setScenarioId]=useState('customer_upload'),[variant,setVariant]=useState('protected'),[text,setText]=useState(''),[file,setFile]=useState<{filename:string;file_base64:string}|null>(null);
 const [decision,setDecision]=useState<Decision|null>(null),[lastRun,setLastRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const upload=useRef<HTMLInputElement>(null);
 const refresh=useCallback(async()=>{const [s,b,e]=await Promise.all([call<Status>('status'),call<Benchmark>('benchmark'),call<Event[]>('events')]);setStatus(s);setPolicy(s.policy);setBenchmark(b);setEvents(e);return s;},[]);
 useEffect(()=>{void refresh().then(s=>setText(s.scenarios[0].protected_text)).catch(e=>setError(e.message));},[refresh]);
 const scenario=status?.scenarios.find(s=>s.id===scenarioId);
 function select(id:string,v:string){setScenarioId(id);setVariant(v);const s=status?.scenarios.find(s=>s.id===id);setText(v==='protected'?s?.protected_text||'':s?.allowed_text||'');setFile(null);if(upload.current)upload.current.value='';setDecision(null);setLastRun(null);setNotice('');}
 async function run(req?:Run){setBusy(true);setError('');setNotice('');setDecision(null);try{const input=req||{scenario_id:scenarioId,variant,...(file?file:{text})};setLastRun(input);const d=await call<Decision>('run',input);setDecision(d);setEvents(await call<Event[]>('events'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function approve(approved:boolean){if(!decision?.approval_id||!lastRun)return;setBusy(true);setError('');try{await call('approvals',{id:decision.approval_id,approved});if(approved)await run({...lastRun,approval_id:decision.approval_id});else{setNotice('승인을 거절했습니다. 내용은 전송되지 않습니다.');setDecision({...decision,approval_id:null});setEvents(await call<Event[]>('events'));}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function edit(index:number,patch:Partial<Policy>){if(policy)setPolicy({...policy,policies:policy.policies.map((p,i)=>i===index?{...p,...patch}:p)});setNotice('');}
 async function publish(){if(!policy)return;setBusy(true);setError('');try{const p=await call<Snapshot>('policy',{expected_revision:policy.revision,policies:policy.policies});setPolicy(p);setNotice(`정책 v${p.revision}을 로컬 Judge에 발행했습니다.`);setEvents(await call<Event[]>('events'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function chooseFile(value:File|undefined){setError('');setDecision(null);setLastRun(null);setFile(null);if(!value)return;if(value.size>4*1024*1024){setError('파일은 최대 4MB까지 가능합니다.');if(upload.current)upload.current.value='';return;}setBusy(true);try{const raw=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('파일을 읽을 수 없습니다.'));r.readAsDataURL(value);});setFile({filename:value.name,file_base64:raw});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="judge-lab"><div className="status-strip"><div><strong>정책 Judge · 독립 판단 API</strong><p>의미 판단은 별도 Jev API에 요청합니다. 로컬 Mac 또는 원격 GPU 서버를 연결할 수 있으며, 수신처는 로컬 시험용입니다.</p></div><span className={`badge ${status?.jev_api_connected?'success':'warning'}`}>{status?.jev_api_connected?'Jev API 연결됨':'Jev API 확인 필요'}</span></div>
 <div className="judge-tabs" role="tablist" aria-label="Judge 메뉴">{[['run','시나리오 실행'],['policy','의미 정책'],['benchmark','모델 비교'],['audit','실행 기록']].map(([id,label])=><button role="tab" aria-selected={tab===id} className={`button ${tab===id?'primary':''}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {error&&<div className="banner error" role="alert">{error}</div>}{notice&&<div className="banner success" role="status">{notice}</div>}
 {!status&&<section className="panel judge-pad"><p>로컬 Judge 상태를 확인하고 있습니다.</p><button className="button" onClick={()=>void refresh().catch(e=>setError(e.message))}>다시 연결</button></section>}
 {status&&tab==='run'&&<><div className="judge-scenarios">{status.scenarios.map((s,i)=><button disabled={busy} aria-pressed={s.id===scenarioId} className={`judge-scenario ${s.id===scenarioId?'selected':''}`} key={s.id} onClick={()=>select(s.id,'protected')}><span>0{i+1}</span><strong>{s.title}</strong><small>{s.description}</small></button>)}</div>
 <div className="judge-grid"><section className="panel"><div className="panel-heading"><div><h2>{scenario?.title}</h2><p>{scenario?.requirement}</p></div></div><div className="judge-pad"><label className="field">시험 조건<select disabled={busy} value={variant} onChange={e=>select(scenarioId,e.target.value)}><option value="protected">보호 대상 예시</option><option value="allowed">허용 대상 예시</option></select></label><p className="judge-help">조건은 로컬 어댑터의 레이블·권한을 설정합니다. 본문의 “공개 승인” 문구는 권한으로 취급하지 않습니다.</p><label className="field">검사 내용<textarea disabled={busy||!!file} value={text} onChange={e=>{setText(e.target.value);setDecision(null);setLastRun(null);}} rows={8}/></label><label className="field">또는 파일 업로드<input disabled={busy} type="file" ref={upload} accept=".xlsx,.docx,.pdf,.txt,.md,.csv,.tsv,.json" onChange={e=>void chooseFile(e.currentTarget.files?.[0])}/></label>{file&&<p className="judge-help">{file.filename} · 파일 내용으로 검사 <button className="text-button" disabled={busy} onClick={()=>{setFile(null);setDecision(null);setLastRun(null);if(upload.current)upload.current.value='';}}>파일 해제</button></p>}<p className="judge-help">최대 4MB. 스캔·이미지·암호화·매크로·수식 등 완전한 검사가 불가능한 파일은 차단합니다. 입력은 DLP·판단 서버 메모리에서 처리하고 감사 기록에 저장하지 않습니다.</p><button className="button primary full" disabled={busy} onClick={()=>void run()}>{busy?'처리 중…':'검사하고 허용된 내용 전달'}</button></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>판단과 전달 결과</h2><p>정책 결정과 수신 확인을 각각 표시합니다.</p></div></div>{!decision?<div className="empty"><h3>{busy?'로컬 모델이 판단하고 있습니다.':'검사 결과가 여기에 표시됩니다.'}</h3><p>차단·검토 대기 상태에서는 수신처를 호출하지 않습니다.</p></div>:<div className="judge-pad"><div className="judge-verdict"><span className={`badge ${decision.action==='block'?'danger':decision.action==='review'?'warning':'success'}`}>{labels[decision.action]}</span><strong>{decision.delivered?'수신 확인됨':decision.reason==='delivery_outcome_unknown'?'수신 여부 불명':'수신 확인 없음'}</strong></div><p>{reasons[decision.reason]||decision.reason}</p><dl className="judge-details"><dt>정책 버전</dt><dd>v{decision.policy_revision}</dd><dt>전체 처리</dt><dd>{decision.elapsed_ms.toFixed(0)} ms</dd><dt>문서 검사</dt><dd>{decision.extraction.format} · {decision.extraction.complete?'추출 완료':'추출 미완료'}</dd><dt>요청 식별</dt><dd className="mono break">{decision.request_digest.slice(0,20)}…</dd>{decision.delivery_id&&<><dt>수신 식별</dt><dd className="mono break">{decision.delivery_id}</dd></>}</dl>{decision.findings.map(f=><div className="judge-finding" key={f.policy_id}><strong>{policy?.policies.find(p=>p.id===f.policy_id)?.name||f.policy_id}</strong><span>{labels[f.choice]} · {(f.scores[f.choice]*100).toFixed(1)}%</span><small>{f.model_id} · {f.latency_ms.toFixed(0)}ms{f.cached?' · 캐시':''}</small></div>)}{decision.findings.length>0&&<p className="judge-help">점수는 선택지 간 상대 점수이며 정답 확률을 보장하지 않습니다.</p>}{decision.action==='review'&&decision.approval_id&&<div className="judge-approval"><strong>내용을 확인한 관리자의 승인이 필요합니다.</strong><p>10분 이내, 동일한 내용·정책·대상에 한해 1회 적용됩니다.</p><div className="judge-tabs"><button className="button primary" disabled={busy} onClick={()=>void approve(true)}>현재 내용 승인 후 전달</button><button className="button" disabled={busy} onClick={()=>void approve(false)}>거절</button></div></div>}</div>}</section></div></>}
 {status&&policy&&tab==='policy'&&<><div className="panel-heading"><div><h2>자연어 의미 정책 · v{policy.revision}</h2><p>모델은 의미를 판단하고, 실행 엔진은 조치·권한·승인을 집행합니다.</p></div><button className="button primary" disabled={busy} onClick={()=>void publish()}>정책 발행</button></div><div className="judge-policies">{policy.policies.map((p,i)=><section className="panel judge-pad" key={p.id}><div className="judge-policy-title"><h3>{p.name}</h3><label><input type="checkbox" checked={p.enabled} disabled={busy} onChange={e=>edit(i,{enabled:e.target.checked})}/> 적용</label></div><label className="field">모델에 묻는 정책 질문<textarea rows={4} value={p.question} disabled={busy} onChange={e=>edit(i,{question:e.target.value})}/></label><label className="field">정책 해당 기준<textarea rows={2} value={p.match_description} disabled={busy} onChange={e=>edit(i,{match_description:e.target.value})}/></label><label className="field">해당 없음 기준<textarea rows={2} value={p.no_match_description} disabled={busy} onChange={e=>edit(i,{no_match_description:e.target.value})}/></label><div className="judge-controls"><label className="field">모델<select value={p.model_id} disabled={busy} onChange={e=>edit(i,{model_id:e.target.value})}>{status.models.map(m=><option key={m.id} value={m.id}>{m.id}</option>)}</select></label><label className="field">해당 시<select value={p.effect} disabled={busy} onChange={e=>edit(i,{effect:e.target.value as Policy['effect']})}><option value="block">차단</option><option value="review">검토 대기</option></select></label><label className="field">최소 점수<input type="number" min="0.5" max="0.999" step="0.001" value={p.threshold} disabled={busy} onChange={e=>edit(i,{threshold:Number(e.target.value)})}/></label><label className="field">불확실할 때<select value={p.uncertainty_action} disabled={busy} onChange={e=>edit(i,{uncertainty_action:e.target.value as Policy['uncertainty_action']})}><option value="review">검토 대기</option><option value="block">차단</option></select></label></div><p className="judge-help">적용: {p.scenarios.map(id=>status.scenarios.find(s=>s.id===id)?.title||id).join(' · ')}</p></section>)}</div><p className="judge-help">변경 내용은 발행 후 적용됩니다. 모델이나 질문 변경 후에는 자체 평가가 필요합니다. ACL·금지 레이블·비밀키 차단은 이 정책에서 해제할 수 없습니다.</p></>}
 {status&&tab==='benchmark'&&<section className="panel"><div className="panel-heading"><div><h2>동일한 고정 합성 평가셋 · 실제 Metal 추론</h2><p>모델당 보정 24건 + 별도 평가 36건. 기본 모델은 Decider 4B입니다.</p></div></div><div className="table-scroll"><table><thead><tr><th>모델</th><th>분류 일치</th><th>민감 오허용</th><th>일반 오차단</th><th>검토 대기</th><th>일반 허용</th><th>p50 / p95</th></tr></thead><tbody>{benchmark?.reports.map(r=><tr key={r.model}><td><strong>{r.model}</strong></td><td>{r.held_out.all.raw_correct}/{r.held_out.all.n}</td><td>{r.held_out.all.false_allow}/18</td><td>{r.held_out.all.false_block}/12</td><td>{r.held_out.all.reviews}/36</td><td>{r.held_out.all.safe_allow}/{r.held_out.all.safe_count}</td><td>{r.p50_ms.toFixed(0)} / {r.p95_ms.toFixed(0)} ms</td></tr>)}</tbody></table></div><div className="judge-pad"><p>Decider 4B는 이 평가에서 일반 사례 12건을 모두 허용했습니다. 민감 오허용 0건은 작은 합성 평가 결과이며 운영 안전성 보장이 아닙니다. 검토 대기가 많아 실제 사내 문서로 추가 평가가 필요합니다.</p><p className="judge-help">분류 일치는 match / no_match / insufficient의 원시 판단입니다. 정책 임계값은 보정셋으로만 정했고, 시간은 짧은 문서의 단일 질문 기준입니다. 다중 정책·파일 추출·콜드 로딩 시간은 별도입니다.</p></div></section>}
 {status&&tab==='audit'&&<section className="panel"><div className="panel-heading"><div><h2>로컬 실행 기록</h2><p>최근 200건 · 원문 미보관 · 로컬 SQLite, 외부 불변 보관 미구현</p></div><button className="button" onClick={()=>void call<Event[]>('events').then(setEvents).catch(e=>setError(e.message))}>기록 새로고침</button></div><div className="table-scroll"><table><thead><tr><th>시각</th><th>이벤트</th><th>판단 / 결과</th><th>근거</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.created_at*1000).toLocaleString('ko-KR')}</td><td>{e.kind}<small>{String(e.data.scenario_id||'')}</small></td><td>{labels[String(e.data.action)]|| (typeof e.data.delivered==='boolean'?(e.data.delivered?'수신 확인':'수신 미확인'):e.data.revision?`v${e.data.revision}`:'—')}</td><td className="break">{reasons[String(e.data.reason)]||String(e.data.reason||e.data.policy_revision&&`정책 v${e.data.policy_revision}`||'메타데이터 기록')}</td></tr>)}</tbody></table></div></section>}
 </div>;
}
