'use client';
import {useState} from 'react';
import {RULE_IDS,RULE_LABELS,type Rules} from '@aidlp/contracts';
import {api,date,type Policy} from './types';
import Icon from './Icon';
export default function PolicyEditor({policy,onApplied,onError}:{policy:Policy;onApplied:()=>Promise<void>;onError:(error:unknown)=>void}){
  const [draft,setDraft]=useState<Rules>({...policy.rules});const [busy,setBusy]=useState(false);
  async function publish(){setBusy(true);try{await api('admin/policy',{expected_revision:policy.revision,rules:draft});await onApplied();}catch(error){onError(error);}finally{setBusy(false);}}
  const blocked=RULE_IDS.filter(id=>draft[id]==='block').length;
  return <div className="policy-grid"><section className="panel"><div className="panel-heading"><div><h2>Sensitive data rules</h2><p>Choose an action when sensitive data is found in outgoing AI requests.</p></div><span className="badge neutral">Shared policy</span></div><div className="rule-list">{RULE_IDS.map(id=><label className="rule-row" key={id}><span><strong>{RULE_LABELS[id]}</strong><small>{id}</small></span><select aria-label={`${RULE_LABELS[id]} Action`} value={draft[id]} onChange={e=>setDraft({...draft,[id]:e.target.value as 'block'|'monitor'})}><option value="block">Block</option><option value="monitor">Monitor and allow</option></select></label>)}</div><div className="panel-footer"><span className="muted">{blocked} blocking · {RULE_IDS.length-blocked} monitoring</span><button className="button primary" disabled={busy} onClick={publish}><Icon name="check" size={17}/>{busy?'Publishing…':'Publish policy'}</button></div></section><aside><section className="panel policy-summary"><span className="eyebrow">CURRENT POLICY</span><div className="version">v{policy.revision}</div><dl><dt>Published</dt><dd>{date(policy.issued_at)}</dd><dt>Expires</dt><dd>{date(policy.expires_at)}</dd></dl><p>Devices receive and verify the published policy. Check the reported revision to confirm application.</p></section><div className="note"><Icon name="shield"/><div><strong>Inspection errors block requests</strong><p>Unsupported request formats and expired policies block requests regardless of monitor settings.</p></div></div><div className="note"><Icon name="devices"/><div><strong>CURRENT SCOPE</strong><p>Target domains are configured on the agent. This screen manages actions by detection type.</p></div></div></aside></div>;
}
